#!/usr/bin/python3

import zlib
import sys
import os

hash_str = sys.argv[1]

with open(".git/objects/" + hash_str[0:2] + "/" + hash_str[2:], "rb") as f:
    inflated = zlib.decompress(f.read())

space = inflated.index(32)

obj_type = inflated[0:space].decode("utf8")

if obj_type == "tree":
    print("hash is tree")
elif obj_type == "commit":
    print("hash is commit")
    null = inflated.index(0)
    tree_hash = inflated[null+1:].decode("utf8").split("\n")[0][5:]
    with open(".git/objects/" + tree_hash[0:2] + "/" + tree_hash[2:], "rb") as f:
        inflated = zlib.decompress(f.read())
elif obj_type != "tree":
    print("No such kek or rofl")
    exit(1)

def write_tree(tree_data):
    null = tree_data.index(0)
    tree_data = tree_data[null+1:]

    while tree_data:
        space = tree_data.find(32)
        if space == -1:
            break

        null = tree_data.index(0)
        filename = tree_data[space+1:null].decode("utf8")
        file_hash = tree_data[null + 1:null + 21].hex()

        with open(".git/objects/" + file_hash[0:2] + "/" + file_hash[2:], "rb") as fi:
            contents = zlib.decompress(fi.read())
            with open(filename, "w") as fo:
                fo.buffer.write(contents[contents.find(0)+1:])

        tree_data = tree_data[null + 21:]
