#!/usr/bin/python

import zlib
import sys
import hashlib
import os

data = sys.stdin.buffer.read()

obj_format = bytearray("blob %d\x00%s", "utf8")
obj_data = obj_format % (len(data), data)

sha1_hasher = hashlib.sha1()
sha1_hasher.update(obj_data)
checksum = sha1_hasher.digest().hex()

os.makedirs(".git/objects/" + checksum[0:2], exist_ok = True)
f = open(".git/objects/" + checksum[0:2] + "/" + checksum[2:], "wb")
f.write(zlib.compress(obj_data))
print(checksum)
