#!/usr/bin/python3

import zlib
import sys
import hashlib
import os

tree_entry_tree_format = bytearray("040000 %s\x00%s", "utf8")
tree_entry_blob_format = bytearray("100644 %s\x00%s", "utf8")
tree_entries = bytearray()

entries = sys.argv[1:]
entries.sort()

for arg in entries:
    [name_str, sha1_str] = arg.split("=")
    name = bytearray(name_str, "utf8")
    sha1 = bytearray.fromhex(sha1_str)
    if name_str.endswith("/"):
        tree_entries += tree_entry_tree_format % (name[0:-1], sha1)
    else:
        tree_entries += tree_entry_blob_format % (name, sha1)

obj_format = bytearray("tree %d\x00%s", "utf8")
obj_data = obj_format % (len(tree_entries), tree_entries)

sha1_hasher = hashlib.sha1()
sha1_hasher.update(obj_data)
checksum = sha1_hasher.digest().hex()

os.makedirs(".git/objects/" + checksum[0:2], exist_ok = True)
f = open(".git/objects/" + checksum[0:2] + "/" + checksum[2:], "wb")
f.write(zlib.compress(obj_data))
print(checksum)
